tap "golangci/tap"
tap "homebrew/cask"

brew "docker-machine-driver-hyperkit"
brew "fzf"
brew "git"
brew "gh"
brew "go"
brew "golangci/tap/golangci-lint"
brew "helm"
brew "icu4c"
brew "jq"
brew "kubernetes-cli"
brew "llvm"
brew "mas"
brew "neovim"
brew "netcat"
brew "ngrep"
brew "node"
brew "pkgconfig"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "socat"
brew "tcpdump"
brew "terraform"
brew "tmux"
brew "tree"
brew "watchman"
brew "wget"

cask "docker"
cask "imageoptim"
cask "macdown"

mas "Xcode", id: 497799835
