tap "github/gh"
tap "golangci/tap"
tap "homebrew/cask"

brew "docker-machine-driver-hyperkit"
brew "fzf"
brew "git"
brew "github/gh/gh"
brew "go"
brew "golangci/tap/golangci-lint"
brew "icu4c"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "llvm"
brew "mas"
brew "neovim"
brew "node"
brew "pkgconfig"
brew "python"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "socat"
brew "tcpdump"
brew "terraform"
brew "tmux"
brew "tree"
brew "watchman"

cask "docker"

mas "Xcode", id: 497799835
